services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "MasterDarkFox"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "HEpatimonjosei2@"
      - key: GENERIC_TIMEZONE
        value: "America/Lima"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "http"
      - key: WEBHOOK_URL
        value: "https://n8n.onrender.com"
